spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: root
    url: jdbc:mysql://127.0.0.1:3306/p9_day03?useUnicode=true&useCursorFetch=true&defaultFetchSize=500&allowMultiQueries=true&rewriteBatchedStatements=true&useSSL=false&serverTimezone=UTC
  redis:
    host: localhost
    port: 6379
    # password:
    database: 0
    # 连接超时时间（毫秒）
    timeout: 5000ms
    # 连接池配置
    jedis:
      pool:
        # 连接池最大连接数（使用负值表示没有限制）
        max-active: 8
        # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-wait: 1ms
        # 连接池中的最大空闲连接
        max-idle: 8
        # 连接池中的最小空闲连接
        min-idle: 0
  rabbitmq:
    host: localhost
    port: 5672
    virtual-host: /Yannick
    username: Yannick
    password: Yannick..
mybatis-plus:
  mapper-locations: classpath:mapper/*Mapper.xml
  # 控制台打印sql语句
  configuration:
    log-impl: org.apache.ibatis.logging.log4j2.Log4j2Impl